version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day:      "sunday"
    assignees:
      - "TsonasIoannis"

  - package-ecosystem: "npm"
    directory: "/front-end"
    schedule:
      interval: "weekly"
      day:      "sunday"
    assignees:
      - "TsonasIoannis"